// Printable documents generated from the live ledger.
import { html, raw } from '../ui/html.js';
import { ic, LOGO_MARK } from '../ui/icons.js';
import { onAction } from '../ui/actions.js';
import { getState, loanById, loanState, appById, dealById, today } from '../data/store.js';
import { money, money0, fmtDate, ratePct, durationLabel, addDays, yearOf, pct } from '../core/util.js';
import { payoffQuote, hasBalloon, escrowAnalysis, computeLoan } from '../core/servicing.js';
import { interestStatement } from '../core/tax.js';
import { analyzeApplication } from '../core/qualify.js';
import { applicantNames } from './app/deals.js';
import { ledgerRows, propertyFacts } from './shared.js';

const seller = () => { const p = getState().profile; return p.entityName ? `${p.entityName} (${p.name})` : p.name || 'The Note Holder'; };
const sellerShort = () => getState().profile.entityName || getState().profile.name || 'The Note Holder';
const addr = (p) => `${p.address}, ${p.city}, ${p.state} ${p.zip || ''}`.trim();

function letterhead(title, sub) {
  return html`<div class="doc-letterhead">
    <div><div class="row" style="gap:10px">${raw(LOGO_MARK)}<div><strong style="font-size:15px">SteadyNote Loan Servicing</strong><div style="font-size:11px;color:#555">Servicing agent for ${sellerShort()}</div></div></div></div>
    <div class="from">servicing@steadynote.example<br>Dated ${fmtDate(today(), 'long')}</div>
  </div>
  <h1>${title}</h1>${sub ? html`<p style="color:#555;margin-bottom:18px">${sub}</p>` : ''}`;
}
const toBorrower = (loan) => html`<p><strong>${loan.borrower.name}</strong>${loan.borrower.contact ? html`<br>Attn: ${loan.borrower.contact}` : ''}<br>${addr(loan.property)}</p>`;
const loanLine = (loan) => html`<p style="color:#555">Loan ${loan.number} · Property: ${addr(loan.property)}</p>`;
const footer = (extra = '') => html`<p class="fine" style="margin-top:28px">${extra}Generated by SteadyNote from the loan ledger. SteadyNote is a servicing agent, not the lender. Questions: servicing@steadynote.example. Prototype document with fictional data.</p>`;

const DOCS = {
  statement(loan) {
    const st = loanState(loan.id);
    const m = st.nextInstallment;
    const y = yearOf(today());
    const yr = st.years[String(y)] || {};
    const recent = ledgerRows(loan, st).filter((r) => r.kind === 'payment').slice(0, 3);
    return html`${letterhead('Mortgage statement', `Statement date ${fmtDate(today())}`)}
      <div class="doc-cols">${toBorrower(loan)}<div class="box"><strong>Amount due: ${money(st.amountDue > 0 ? st.amountDue : m ? m.total : 0)}</strong><br>Payment due date: ${m ? fmtDate(m.due) : '—'}<br>If paid after ${m ? fmtDate(addDays(m.due, st.grace)) : '—'}, a ${money(st.lateFee)} late charge applies.${loan.autopay?.enabled ? html`<br><em>Autopay will draft ${loan.autopay.account} on the due date.</em>` : ''}</div></div>
      ${loanLine(loan)}
      <h2>Explanation of amount due</h2>
      <table><tbody>
        <tr><td>Principal</td><td class="num">${money(m ? m.principal : 0)}</td></tr>
        <tr><td>Interest</td><td class="num">${money(m ? m.interest : 0)}</td></tr>
        ${m && m.escrow ? html`<tr><td>Escrow (taxes & insurance)</td><td class="num">${money(m.escrow)}</td></tr>` : ''}
        <tr><td>Regular monthly payment</td><td class="num">${money(m ? m.total : 0)}</td></tr>
        ${st.pastDue.length ? html`<tr><td>Past-due installments (${st.pastDue.length})</td><td class="num">${money(st.pastDue.reduce((s, x) => s + x.total, 0) - (st.pastDue.includes(m) ? m.total : 0))}</td></tr>` : ''}
        ${st.feesOutstanding ? html`<tr><td>Late & other charges</td><td class="num">${money(st.feesOutstanding)}</td></tr>` : ''}
        ${st.suspense ? html`<tr><td>Less partial payment held (suspense)</td><td class="num">−${money(st.suspense)}</td></tr>` : ''}
        <tr class="total"><td>Total amount due</td><td class="num">${money(st.amountDue > 0 ? st.amountDue : m ? m.total : 0)}</td></tr>
      </tbody></table>
      <div class="doc-cols">
        <div><h2>Account information</h2><table><tbody>
          <tr><td>Outstanding principal</td><td class="num">${money(st.principalBalance)}</td></tr>
          <tr><td>Interest rate</td><td class="num">${ratePct(loan.terms.ratePct)} fixed</td></tr>
          ${loan.escrow?.enabled ? html`<tr><td>Escrow balance</td><td class="num">${money(st.escrowBalance)}</td></tr>` : ''}
          <tr><td>Maturity${hasBalloon(loan.terms) ? ' (balloon)' : ''}</td><td class="num">${fmtDate(st.maturityDate)}</td></tr>
        </tbody></table></div>
        <div><h2>Paid year to date (${y})</h2><table><tbody>
          <tr><td>Interest</td><td class="num">${money(yr.interest || 0)}</td></tr>
          <tr><td>Principal</td><td class="num">${money(yr.principal || 0)}</td></tr>
          <tr><td>Escrow</td><td class="num">${money(yr.escrowIn || 0)}</td></tr>
          <tr><td>Charges</td><td class="num">${money(yr.fees || 0)}</td></tr>
        </tbody></table></div>
      </div>
      <h2>Recent payments</h2>
      <table><thead><tr><th>Date</th><th>Description</th><th class="num">Amount</th></tr></thead><tbody>${recent.length ? recent.map((r) => html`<tr><td>${fmtDate(r.date)}</td><td>${r.desc}</td><td class="num">${money(r.amount)}</td></tr>`) : html`<tr><td colspan="3">No payments yet.</td></tr>`}</tbody></table>
      ${footer()}`;
  },

  payoff(loan, q) {
    const st = loanState(loan.id);
    const date = q.date || addDays(today(), 10);
    if (st.paidOffDate) {
      const e = [...st.ledger].reverse().find((x) => x.kind === 'payment' && x.tx?.applyTo === 'payoff');
      return html`${letterhead('Paid-in-full letter', `Loan ${loan.number}`)}${toBorrower(loan)}
        <p>This confirms that loan ${loan.number}, secured by ${addr(loan.property)}, was <strong>paid in full on ${fmtDate(st.paidOffDate)}</strong>${e ? html` with a final payment of ${money(e.amount)}` : ''}.</p>
        ${loan.release ? html`<p>A ${loan.release.document.toLowerCase()} was recorded on ${fmtDate(loan.release.recordedAt)} (${loan.release.county}).</p>` : html`<p>The lien release is being prepared for recording.</p>`}
        <p>Thank you for your payments. ${sellerShort()}</p>${footer()}`;
    }
    const p = payoffQuote(loan, st, date);
    return html`${letterhead('Payoff statement', `Good through ${fmtDate(date, 'long')}`)}
      ${toBorrower(loan)}${loanLine(loan)}
      <table><tbody>
        <tr><td>Unpaid principal balance</td><td class="num">${money(p.principal)}</td></tr>
        <tr><td>Interest ${p.days >= 0 ? `from ${fmtDate(p.through)} to ${fmtDate(date)} (${p.days} days at ${money(Math.round(p.perDiem))}/day)` : '(credit for interest prepaid)'}</td><td class="num">${money(p.interest)}</td></tr>
        ${p.fees ? html`<tr><td>Late & other charges</td><td class="num">${money(p.fees)}</td></tr>` : ''}
        ${p.escrowShortage ? html`<tr><td>Escrow shortage</td><td class="num">${money(p.escrowShortage)}</td></tr>` : ''}
        ${p.suspense ? html`<tr><td>Less funds held in suspense</td><td class="num">−${money(p.suspense)}</td></tr>` : ''}
        <tr class="total"><td>Total payoff amount</td><td class="num">${money(p.total)}</td></tr>
      </tbody></table>
      <div class="box">Interest accrues at <strong>${money(Math.round(p.perDiem))} per day</strong> after ${fmtDate(date)}. Funds received after that date must include additional per-diem interest.${p.escrowRefund ? ` The escrow balance of ${money(p.escrowRefund)} will be refunded to the borrower after payoff.` : ''}</div>
      <p>Send payoff funds by wire or cashier’s check payable to <strong>${sellerShort()}</strong>, referencing loan ${loan.number}. On receipt of the full amount, the note holder will release the lien.</p>
      ${footer('Figures assume no further payments or charges before the payoff date and are subject to final verification. ')}`;
  },

  interest(loan, q) {
    const year = Number(q.year) || yearOf(today()) - 1;
    const s = interestStatement(loan, year);
    const p = getState().profile;
    const cur = year >= yearOf(today());
    return html`${letterhead(`${year} mortgage interest statement${cur ? ' (year to date)' : ''}`, 'Seller-financed loan: for your federal income tax records')}
      <div class="doc-cols">
        <div><h2>Recipient / lender</h2><p>${seller()}<br>${p.city ? `${p.city}, ${p.state}` : ''}<br>TIN: provided securely on request</p></div>
        <div><h2>Payer / borrower</h2><p>${loan.borrower.name}<br>${addr(loan.property)}<br>TIN: ${loan.borrower.tinOnFile ? `•••-••-${loan.borrower.tinLast4}` : 'not on file'}</p></div>
      </div>
      ${loanLine(loan)}
      <table><tbody>
        <tr><td><strong>Mortgage interest received from payer</strong></td><td class="num"><strong>${money(s.interest)}</strong></td></tr>
        <tr><td>Outstanding principal on January 1, ${year}</td><td class="num">${money(s.balanceStart)}</td></tr>
        <tr><td>Principal paid</td><td class="num">${money(s.principal)}</td></tr>
        <tr><td>Outstanding principal on December 31, ${year}${cur ? ' (projected with no further payments)' : ''}</td><td class="num">${money(s.balanceEnd)}</td></tr>
        ${s.taxesPaid ? html`<tr><td>Real estate taxes paid from escrow</td><td class="num">${money(s.taxesPaid)}</td></tr>` : ''}
        ${s.insurancePaid ? html`<tr><td>Insurance paid from escrow</td><td class="num">${money(s.insurancePaid)}</td></tr>` : ''}
        ${s.lateCharges ? html`<tr><td>Late charges paid</td><td class="num">${money(s.lateCharges)}</td></tr>` : ''}
      </tbody></table>
      <div class="box"><strong>Borrower:</strong> if this is your home, you may be able to deduct the interest on Schedule A (line 8b, interest not reported on Form 1098). You must list the lender’s name, address and taxpayer ID. <strong>Lender:</strong> report the interest as income on Schedule B and list the borrower’s name, address and SSN if they used the property as a personal residence.</div>
      ${footer('General information, not tax advice. ')}`;
  },

  schedule(loan) {
    const st = loanState(loan.id);
    const rows = [...st.paid.map((x) => ({ ...x, done: true })), ...st.unpaid];
    return html`${letterhead('Amortization schedule', `${loan.number} · ${money0(loan.terms.principal)} at ${ratePct(loan.terms.ratePct)} over ${durationLabel(loan.terms.amortMonths)}${hasBalloon(loan.terms) ? `, balloon after ${durationLabel(loan.terms.balloonMonths)}` : ''}`)}
      ${loanLine(loan)}
      <table><thead><tr><th class="num">#</th><th>Due</th><th class="num">Payment</th><th class="num">Interest</th><th class="num">Principal</th><th class="num">Balance</th><th>Status</th></tr></thead>
      <tbody>${(() => { let b = loan.terms.principal; return rows.map((r) => { b -= r.principal; return html`<tr><td class="num">${r.n}</td><td>${fmtDate(r.due)}</td><td class="num">${money(r.pi)}</td><td class="num">${money(r.interest)}</td><td class="num">${money(r.principal)}</td><td class="num">${money(Math.max(0, b))}</td><td>${r.done ? `Paid ${fmtDate(r.paidDate, 'numeric')}` : r.balloon ? 'Balloon' : ''}</td></tr>`; }); })()}</tbody></table>
      ${footer('Future rows assume on-time payment of the scheduled amount. ')}`;
  },

  terms(loan) {
    const t = loan.terms;
    const st = loanState(loan.id);
    return html`${letterhead('Loan terms summary', loan.number)}
      <div class="doc-cols"><div><h2>Parties</h2><p><strong>Lender (note holder):</strong> ${seller()}<br><strong>Borrower:</strong> ${loan.borrower.name}<br><strong>Servicer:</strong> SteadyNote Loan Servicing</p></div>
      <div><h2>Property</h2><p>${addr(loan.property)}<br>${propertyFacts(loan.property)}</p></div></div>
      <table><tbody>
        <tr><td>Purchase price</td><td class="num">${money(t.salePrice)}</td></tr>
        <tr><td>Down payment</td><td class="num">${money(t.downPayment)}</td></tr>
        <tr><td>Amount financed</td><td class="num">${money(t.principal)}</td></tr>
        <tr><td>Interest rate</td><td class="num">${ratePct(t.ratePct)} fixed</td></tr>
        <tr><td>Amortization</td><td class="num">${durationLabel(t.amortMonths)}</td></tr>
        <tr><td>Monthly principal & interest</td><td class="num">${money(st.payment)}</td></tr>
        ${loan.escrow?.enabled ? html`<tr><td>Monthly escrow (initial)</td><td class="num">${money(loan.escrow.monthly)}</td></tr>` : ''}
        <tr><td>First payment date</td><td class="num">${fmtDate(t.firstDue)}</td></tr>
        <tr><td>${hasBalloon(t) ? 'Balloon payment due' : 'Maturity date'}</td><td class="num">${fmtDate(st.maturityDate)}</td></tr>
        <tr><td>Grace period / late charge</td><td class="num">${st.grace} days / ${t.lateFee?.pct ?? 5}% of P&I (${money(st.lateFee)})</td></tr>
        <tr><td>Prepayment</td><td class="num">Allowed anytime without penalty</td></tr>
      </tbody></table>${footer()}`;
  },

  escrow(loan) {
    const st = loanState(loan.id);
    const ea = escrowAnalysis(loan, st, today());
    if (!ea) return html`<p>No escrow on this loan.</p>`;
    return html`${letterhead('Annual escrow account statement', `Projection for the next 12 months`)}${toBorrower(loan)}${loanLine(loan)}
      <table><tbody><tr><td>Current escrow balance</td><td class="num">${money(st.escrowBalance)}</td></tr><tr><td>Projected annual disbursements</td><td class="num">${money(ea.annual)}</td></tr><tr><td>Required cushion (1/6 of annual)</td><td class="num">${money(ea.cushion)}</td></tr><tr><td>Projected low point</td><td class="num">${money(ea.lowPoint)} (${fmtDate(ea.lowMonth, 'month')})</td></tr><tr><td>${ea.shortage ? 'Shortage' : 'Surplus'}</td><td class="num">${money(ea.shortage || ea.surplus)}</td></tr><tr class="total"><td>New monthly escrow payment</td><td class="num">${money(ea.recommended)}</td></tr></tbody></table>
      <table><thead><tr><th>Month</th><th class="num">Deposit</th><th class="num">Disbursement</th><th class="num">Balance</th></tr></thead><tbody>${ea.months.map((m) => html`<tr><td>${fmtDate(m.date, 'month')}</td><td class="num">${money(m.deposit)}</td><td class="num">${m.out ? money(m.out) : ''}</td><td class="num">${money(m.balance)}</td></tr>`)}</tbody></table>${footer()}`;
  },

  'late-notice'(loan) {
    const st = loanState(loan.id);
    const m = st.nextInstallment;
    return html`${letterhead('Notice of late payment', loan.number)}${toBorrower(loan)}
      <p>Dear ${loan.borrower.contact || loan.borrower.name},</p>
      <p>Our records show the payment due <strong>${m ? fmtDate(m.due, 'long') : ''}</strong> on your loan for ${addr(loan.property)} has not been received. As of ${fmtDate(today(), 'long')}, the account is <strong>${st.dpd} days past due</strong>.</p>
      <table><tbody><tr><td>Past-due installments</td><td class="num">${money(st.pastDue.reduce((s, x) => s + x.total, 0))}</td></tr><tr><td>Late charges</td><td class="num">${money(st.feesOutstanding)}</td></tr>${st.suspense ? html`<tr><td>Less funds on hand</td><td class="num">−${money(st.suspense)}</td></tr>` : ''}<tr class="total"><td>Amount needed to bring the loan current</td><td class="num">${money(st.amountDue)}</td></tr></tbody></table>
      <p>Please pay through your borrower portal or contact us right away if you’re having difficulty. We’re glad to discuss options with ${sellerShort()}.</p>
      <p>Sincerely,<br>SteadyNote Loan Servicing, on behalf of ${sellerShort()}</p>${footer()}`;
  },

  'default-notice'(loan) {
    const st = loanState(loan.id);
    const cure = addDays(today(), 30);
    return html`${letterhead('Notice of default and right to cure', loan.number)}
      <div class="doc-draft"><strong>Template for attorney review.</strong> Default and foreclosure notices are governed by your note, deed of trust and state law. Have an attorney confirm timing and content before sending.</div>
      ${toBorrower(loan)}
      <p>You are in default under the promissory note and security instrument for ${addr(loan.property)} for failure to make the payments described below.</p>
      <table><tbody><tr><td>Amount required to cure</td><td class="num">${money(st.amountDue)}</td></tr><tr><td>Days past due</td><td class="num">${st.dpd}</td></tr></tbody></table>
      <p>To cure the default, pay <strong>${money(st.amountDue)}</strong> plus any payments and charges that come due, on or before <strong>${fmtDate(cure, 'long')}</strong>. If the default is not cured by that date, the note holder may accelerate the loan and pursue remedies available under the security instrument and applicable law.</p>
      <p>You may have the right to reinstate after acceleration and to raise any defense in a foreclosure proceeding. If you need help, contact a HUD-approved housing counselor.</p>${footer()}`;
  },

  note(loan) {
    const t = loan.terms;
    const st = loanState(loan.id);
    return html`<div class="doc-draft"><strong>Sample for discussion. Not for signature.</strong> Promissory notes and security instruments must meet your state’s requirements. SteadyNote partner attorneys prepare final closing documents.</div>
      <h1 style="text-align:center">PROMISSORY NOTE</h1>
      <p style="text-align:center;color:#555">(Fixed rate${hasBalloon(t) ? ', balloon' : ''}; secured by deed of trust or mortgage)</p>
      <p><strong>Principal amount:</strong> ${money(t.principal)} &nbsp; <strong>Date:</strong> ${fmtDate(t.closingDate, 'long')} &nbsp; <strong>Property:</strong> ${addr(loan.property)}</p>
      <h2>1. Promise to pay</h2><p>For value received, ${loan.borrower.name} (“Borrower”) promises to pay ${seller()} (“Lender”) the principal amount above, plus interest, at the place Lender designates, including through Lender’s servicing agent.</p>
      <h2>2. Interest</h2><p>Interest accrues on unpaid principal at a fixed yearly rate of ${ratePct(t.ratePct)}, calculated on a 30/360 basis for regular installments and per diem on an actual/365 basis for payoff.</p>
      <h2>3. Payments</h2><p>Borrower will pay ${money(st.payment)} per month beginning ${fmtDate(t.firstDue, 'long')} and on the same day of each month after that.${hasBalloon(t) ? ` All remaining principal and accrued interest are due on ${fmtDate(st.maturityDate, 'long')} (the “Maturity Date”).` : ` Payments continue until all amounts are paid, no later than ${fmtDate(st.maturityDate, 'long')}.`} ${loan.escrow?.enabled ? 'Borrower will also pay monthly escrow deposits for property taxes and insurance as required by the security instrument.' : ''}</p>
      <h2>4. Application of payments</h2><p>Payments are applied first to interest due, then to principal due, then to escrow, and then to late charges and other amounts due. Payments exceeding the amount due reduce principal unless Borrower directs otherwise.</p>
      <h2>5. Prepayment</h2><p>Borrower may prepay all or part of the principal at any time without penalty.</p>
      <h2>6. Late charge</h2><p>If Lender has not received a full monthly payment by the end of ${st.grace} calendar days after its due date, Borrower will pay a late charge of ${t.lateFee?.pct ?? 5}% of the overdue principal and interest payment, once per late payment.</p>
      <h2>7. Default</h2><p>If Borrower fails to pay any amount when due and does not cure after written notice as required by law, Lender may require immediate payment of the full unpaid principal and interest.</p>
      <h2>8. Security</h2><p>This Note is secured by a deed of trust or mortgage on the Property dated the same date.</p>
      <div class="sig"><div>Borrower signature / date</div><div>Borrower signature / date</div></div>
      ${footer()}`;
  },

  atr(app) {
    const d = dealById(app.dealId);
    const an = analyzeApplication(app, d);
    return html`${letterhead('Ability-to-Repay worksheet', `${applicantNames(app)} · ${d.property.address}`)}
      <p>Good-faith determination of the consumer’s reasonable ability to repay, documenting the factors in 12 CFR 1026.43(c)(2). Prepared ${fmtDate(today(), 'long')}.</p>
      <table><thead><tr><th>#</th><th>Factor</th><th>Finding</th><th>Verification</th></tr></thead><tbody>${an.atr.map((f, i) => html`<tr><td>${i + 1}</td><td>${f.factor}</td><td>${f.value}</td><td>${f.verified ? 'Verified' : 'Stated'}: ${f.source}</td></tr>`)}</tbody></table>
      <h2>Summary</h2>
      <table><tbody><tr><td>Housing payment (PITI)</td><td class="num">${money(an.housing.total)}</td></tr><tr><td>Debt-to-income</td><td class="num">${pct(an.back)}</td></tr><tr><td>Residual income (est.)</td><td class="num">${money0(an.residual)}</td></tr><tr><td>Reserves after closing</td><td class="num">${Math.max(0, an.reserveMonths).toFixed(1)} months</td></tr><tr><td>SteadyNote score</td><td class="num">${an.score}/100 (${an.grade})</td></tr></tbody></table>
      <div class="box">${app.decision?.atrAttested ? html`<strong>Determination:</strong> ${seller()} determined in good faith on ${fmtDate(app.decision.at, 'long')} that the consumer has a reasonable ability to repay.` : html`<strong>Determination:</strong> not yet attested.`}</div>
      <div class="sig"><div>Seller / note holder</div><div>Date</div></div>${footer('Retain with your loan records for at least three years after closing. ')}`;
  },

  adverse(app) {
    const d = dealById(app.dealId);
    const sc = app.screening;
    const reasons = app.decision?.reasons?.length ? app.decision.reasons : ['We do not grant credit on the terms you requested'];
    const a0 = app.applicants[0];
    return html`${letterhead('Notice of action taken', `Your application for ${d.property.address}`)}
      <p><strong>${applicantNames(app)}</strong><br>${a0.email}</p>
      <p>Thank you for applying to purchase ${addr(d.property)} with seller financing from ${seller()}. After careful review, we are unable to approve your application at this time.</p>
      <h2>Principal reason(s) for our decision</h2><ul>${reasons.map((r) => html`<li>${r}</li>`)}</ul>
      ${sc ? html`<h2>Your credit score</h2><p>Our decision was based in whole or in part on information from a consumer credit report.</p><table><tbody><tr><td>Your credit score</td><td class="num">${sc.creditScore}</td></tr><tr><td>Range of possible scores</td><td class="num">300 – 850</td></tr><tr><td>Date</td><td class="num">${fmtDate(sc.completedAt)}</td></tr></tbody></table>
      <p>The consumer reporting agency that provided the report did not make this decision and can’t explain why it was made. You have the right to a free copy of your report from that agency if you ask within 60 days, and the right to dispute the accuracy or completeness of any information in it.</p>` : ''}
      <div class="box"><strong>Your rights under the Equal Credit Opportunity Act.</strong> The federal Equal Credit Opportunity Act prohibits creditors from discriminating against credit applicants on the basis of race, color, religion, national origin, sex, marital status, or age (provided the applicant has the capacity to enter into a binding contract); because all or part of the applicant’s income derives from any public assistance program; or because the applicant has in good faith exercised any right under the Consumer Credit Protection Act. The federal agency that administers compliance with this law concerning this creditor is the Federal Trade Commission, Washington, DC 20580.</div>
      <p>Sincerely,<br>${seller()}</p>${footer('Sample notice for review. Add the name, address and phone number of the consumer reporting agency before sending. ')}`;
  },
};

export const docView = {
  layout: 'doc',
  title: (ctx) => ({ statement: 'Statement', payoff: 'Payoff statement', interest: 'Interest statement', schedule: 'Amortization schedule', terms: 'Loan terms', escrow: 'Escrow statement', 'late-notice': 'Late notice', 'default-notice': 'Notice of default', note: 'Promissory note (sample)', atr: 'ATR worksheet', adverse: 'Adverse action notice' }[ctx.params.kind] || 'Document'),
  render(ctx) {
    const { kind, id } = ctx.params;
    const fn = DOCS[kind];
    const isApp = kind === 'atr' || kind === 'adverse';
    const subject = isApp ? appById(id) : loanById(id);
    const back = isApp ? `#/app/applicants/${id}` : `#/app/loans/${id}`;
    const body = fn && subject ? fn(subject, ctx.query) : html`<p>Document not found.</p>`;
    return html`<div class="doc-toolbar">
        <a class="btn btn-secondary btn-sm" href="${back}">${ic('arrowLeft', { size: 15 })} Back</a>
        <div class="btn-row"><span class="xs muted hide-sm">Use your browser’s print dialog to save as PDF</span><button type="button" class="btn btn-primary btn-sm" data-action="print">${ic('printer', { size: 15 })} Print / Save PDF</button></div>
      </div>
      <article class="doc-page">${body}</article>`;
  },
};

onAction({ print: () => window.print() });

export { computeLoan };
